import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/UI/Header";
import {useAtom} from "jotai";
import { accountAtom } from '~/store';

const Home: NextPage = () => {
  const [account] = useAtom(accountAtom);

  return (
    <>
      <Head>
        <title>Braindump</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {account ? "Hello we are logged in" : "We are logged out"}
      </main>
    </>
  );
};

export default Home;
