import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/layout/Header";
import {useAtom} from "jotai";
import { accountAtom } from '~/store';
import Transcribe from "~/components/Transcribe";

const Home: NextPage = () => {
  const [account] = useAtom(accountAtom);

  return (
    <>
      <Head>
        <title>Braindump</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {account ? 
          <div>
            <h2>logged in</h2>
            <Transcribe></Transcribe>
          </div> : 
          <h2>logged out</h2>
        }
      </main>
    </>
  );
};

export default Home;
